# Generated by Django 5.2.6 on 2025-10-22 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work08', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='memo_images/'),
        ),
    ]
