# Generated by Django 5.2.6 on 2025-11-12 02:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=100, verbose_name='カテゴリ（例: 食費・趣味）')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.PositiveIntegerField()),
                ('source', models.CharField(max_length=100, verbose_name='収入の種類（例: バイト代）')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
            ],
        ),
        migrations.CreateModel(
            name='SavingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_name', models.CharField(max_length=100, verbose_name='目標名（例: 新しいPC）')),
                ('target_amount', models.PositiveIntegerField(verbose_name='目標金額')),
                ('target_date', models.DateField(verbose_name='目標日')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
